-- AUTO-GENERATED by ClassThemeBuilder.cs — class theme registry snippet

    TheWarrior = MakeClassTheme(
        "TheWarrior", "The Warrior",
        { 0.78, 0.61, 0.43 },
        { 1, 0.55, 0.25 },
        { 0.072, 0.048, 0.03 },
        { 0.12, 0.08, 0.05 }
    ),
    TheHunter = MakeClassTheme(
        "TheHunter", "The Hunter",
        { 0.67, 0.83, 0.45 },
        { 0.55, 1, 0.35 },
        { 0.06, 0.084, 0.036 },
        { 0.1, 0.14, 0.06 }
    ),
    TheRogue = MakeClassTheme(
        "TheRogue", "The Rogue",
        { 1, 0.96, 0.41 },
        { 1, 0.92, 0.3 },
        { 0.072, 0.066, 0.036 },
        { 0.12, 0.11, 0.06 }
    ),
    ThePriest = MakeClassTheme(
        "ThePriest", "The Priest",
        { 1, 1, 1 },
        { 1, 0.95, 0.7 },
        { 0.084, 0.078, 0.108 },
        { 0.14, 0.13, 0.18 }
    ),
    TheShaman = MakeClassTheme(
        "TheShaman", "The Shaman",
        { 0, 0.44, 0.87 },
        { 0.35, 0.85, 1 },
        { 0.03, 0.06, 0.108 },
        { 0.05, 0.1, 0.18 }
    ),
    TheMage = MakeClassTheme(
        "TheMage", "The Mage",
        { 0.25, 0.78, 0.92 },
        { 0.45, 0.9, 1 },
        { 0.048, 0.084, 0.132 },
        { 0.08, 0.14, 0.22 }
    ),
    TheWarlock = MakeClassTheme(
        "TheWarlock", "The Warlock",
        { 0.53, 0.53, 0.93 },
        { 0.75, 0.35, 1 },
        { 0.084, 0.036, 0.108 },
        { 0.14, 0.06, 0.18 }
    ),
    TheMonk = MakeClassTheme(
        "TheMonk", "The Monk",
        { 0, 1, 0.59 },
        { 0.35, 1, 0.7 },
        { 0.036, 0.084, 0.06 },
        { 0.06, 0.14, 0.1 }
    ),
    TheDruid = MakeClassTheme(
        "TheDruid", "The Druid",
        { 1, 0.49, 0.04 },
        { 1, 0.72, 0.25 },
        { 0.096, 0.06, 0.03 },
        { 0.16, 0.1, 0.05 }
    ),
    TheDeathKnight = MakeClassTheme(
        "TheDeathKnight", "The Death Knight",
        { 0.77, 0.12, 0.23 },
        { 1, 0.35, 0.4 },
        { 0.072, 0.024, 0.036 },
        { 0.12, 0.04, 0.06 }
    ),
    TheEvoker = MakeClassTheme(
        "TheEvoker", "The Evoker",
        { 0.2, 0.58, 0.5 },
        { 0.4, 1, 0.85 },
        { 0.036, 0.072, 0.066 },
        { 0.06, 0.12, 0.11 }
    ),
